### ISSUE TITLE
convert budget in brief 16 to json

### ISSUE THREAD

**Issue by meganmckissack** [hackoregon/team-budget#1]

**Comment by meganmckissack** [comment]
need to structure the data in a more normalized form first

**Comment by MikeTheCanuck** [comment]
I believe this has been covered by commit https://github.com/hackoregon/team-budget/commit/570944ca10e07297be079f981102fb8d805a3dd7.

The API endpoints are now emitting JSON data, and are able to import directly from the CSVs (without having to convert CSV to JSON).

Is there anything else this was intended to address, that we still need to do?

**Comment by jimtyhurst** [comment]
I agree with Mike that the requirement underlying this issue, i.e. ability for web service to provide JSON, has already been implemented.
