### ISSUE TITLE
Verify Production DB has no duplicate rows

### ISSUE THREAD

**Issue by hassanshamim** [hackoregon/team-budget#115]
I haven't been very closely involved with the actual budget DB we are extracting our data from, but every now and then I'll compare my local api responses with the production ones and I see a large difference in the number of rows in certain tables.

Just review the number of records in each table in the production DB to ensure it's accurate.  **Must** happen before demo-day.

**Comment by MikeTheCanuck** [comment]
Being addressed in #134
