### ISSUE TITLE
Fix staticfiles in production

### ISSUE THREAD

**Issue by hassanshamim** [hackoregon/team-budget#116]
Django assumes our webserver (nginx?) will server the static files in production, which is why our swagger views are all messed up.

Simplest fix as far as I can tell is adding and enabling this:
https://github.com/kennethreitz/dj-static  Following the directions in the readme should be sufficient.

**Comment by MikeTheCanuck** [comment]
This probably would've worked too, but at today's mini-hack Brian Grant walked me through configuring `whitenoise` and it has definitely fixed our missing Swagger UI.  I've deployed the resulting container and generated PR #123 to address this
