### ISSUE TITLE
duplicate records in OCRB table in Integration environment PostgreSQL database

### ISSUE THREAD

**Issue by mxmoss** [hackoregon/team-budget#134]
Hassan  @hassanshamim says he thinks we've got some duplicate records in the staged DB.
Specifically, the count of OCRB records differs from his local db.
-- This counts the OCRB records
select count(*) from public.budget_app_ocrb
-- returns 13731 OCRB records
He thinks it should be closer to 300

**Comment by mxmoss** [comment]
-- Turns out we've got 52x the duplicates of OCRB records
SELECT source_document, service_area, bureau, budget_category, amount, 
       fy, budget_type, count(*)
  FROM public.budget_app_ocrb
group by
 source_document, service_area, bureau, budget_category, amount, 
       fy, budget_type
having count(*) > 1

-- KPM is OK
SELECT source_document, service_area, bureau, key_performance_measures, 
       fy, budget_type, amount, units, count(*)
  FROM public.budget_app_kpm
group by source_document, service_area, bureau, key_performance_measures, 
       fy, budget_type, amount, units
 having count(*) > 1

-- History is OK
SELECT
 fund_center_code, fund_code, functional_area_code, object_code, 
       fund_center_name, fund_name, functional_area_name, accounting_object_name, 
       service_area_code, program_code, sub_program_code, fund_center, 
       division_code, bureau_code, bureau_name, fiscal_year, amount, count(*)
  FROM public.budget_app_budgethistory
group by
 fund_center_code, fund_code, functional_area_code, object_code, 
       fund_center_name, fund_name, functional_area_name, accounting_object_name, 
       service_area_code, program_code, sub_program_code, fund_center, 
       division_code, bureau_code, bureau_name, fiscal_year, amount
having count(*)  > 1

**Comment by MikeTheCanuck** [comment]
Seems like we have two options to address this:

1. Write a SQL script to find and delete all the excess records
2. Drop the table's contents and re-run the `importcsv` operation on that one table's data.

I feel like the second would work fine and be less trouble.  There's no unique data we need to preserve in that table - it should all still be in the source CSV we used the first (fifty-two) time(s) around.

**Comment by jimtyhurst** [comment]
> 2. Drop the table's contents and re-run the importcsv operation on that one table's data.

This is definitely the correct approach and the easiest approach.

**Comment by MikeTheCanuck** [comment]
Here's what I did:

```
$ budget_proj/manage.py shell
Python 3.5.2 (default, Oct 11 2016, 05:05:28) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.38)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from budget_app.models import OCRB
>>> OCRB.objects.all().delete()
(13731, {'budget_app.OCRB': 13731})
>>> exit()
```

Then I ran:

```
$ budget_proj/manage.py importcsv budget_app.OCRB ./Data/Budget_in_Brief_OCRB_data_All_Years.csv "Source document:source_document" "Service Area:service_area" "Bureau:bureau" "Budget Category:budget_category" "Amount:amount" "Fiscal Year:fiscal_year" "Budget Type:budget_type"
```

After that, PgAdmin reported 264 rows in OCRB table.

**Comment by hassanshamim** [comment]
Thanks Mike!  I verified these changes are reflected in prod.
