### ISSUE TITLE
service.civicpdx.org’s server DNS address could not be found

### ISSUE THREAD

**Issue by jimtyhurst** [hackoregon/team-budget#160]
I am still getting an error message when trying to access the web service:
```
The web service is not available
service.civicpdx.org’s server DNS address could not be found.
```
I see that error when I try to access endpoints within the service. For example, `http://service.civicpdx.org/budget/` or `http://service.civicpdx.org/budget/history/service_area/`

I think this is the same error that showed up during the demo, but now I am trying to access the service from my house, so that rules out a local OMSI network issue. That was frustrating, because I verified that the web service was running this afternoon, so not sure what happened in the meantime. The most recent deployment was 2 days ago, so it was not due to a recent code change.

**Comment by jimtyhurst** [comment]
I do not know who fixed it or how it was fixed, but the DNS problem was resolved and the web service is available again at http://service.civicpdx.org/budget/

**Comment by MikeTheCanuck** [comment]
There was an underinformed individual (who shall not be named here) who decided to move the SOA for the DNS zone `civicpdx.org` to DigitalOcean, during the demos.

That action has been reversed and we're all doing fine again, thank you.
