### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by maryannet** [hackoregon/team-budget#27]
Please write documentation so that other people can recreate what you have accomplished.   For example: moving SQL server image to PostgreSQL. Write down the steps you take. Document what you are doing including mistakes and crazy error messages. This is a learning process. We learn from each other.

**Comment by jimtyhurst** [comment]
I guess we can leave this issue open as a reminder, but we already have a couple of examples in the repository. So we should consider closing this issue.

- See the top-level [README.md](https://github.com/hackoregon/team-budget/blob/master/README.md) for shell commands to execute the `importcsv.py` script for loading data from CSV files in the repository to a relational database.
- See the [Data/README_DataSources.md](https://github.com/hackoregon/team-budget/blob/master/Data/README_DataSources.md) file as a starting point for documenting how we transform data received from the City of Portland into data that we load into the Hack Oregon Budget project database.
- See the [R script](https://github.com/hackoregon/team-budget/blob/master/R/HackOregon_hx_budget_data_ASV2_transform.R) for transforming historical data. This provides a repeatable process for an automated transformation from a spreadsheet received from the City of Portland to a CSV of tidy data that can be loaded into a relational database.

**Comment by maryannet** [comment]
Please keep this open. I want to capture directions and thoughts for future Hack Oregon participants. Good writing so far. Keep writing clear directions and how to's . Also include pain-points and what didn't work.

**Comment by maryannet** [comment]
Please keep this open. a lot of good work has been done. More needs to be written.

**Comment by MikeTheCanuck** [comment]
@maryannet I assume your desire to keep this open means you're currently contributing to the docs - please let us know where you are contributing so no one else collides with your efforts.

**Comment by maryannet** [comment]
After Demo night I will look over documentation. This in an invitation to keep people writing. No one will collide with my efforts. I can tie pieces of writing  together.

**Comment by MikeTheCanuck** [comment]
Cleaning up old unresolved issues.  Issues need a specific request to be productive, so I'm closing this.  Any specific documentation needs should be addressed as a new, explicit issue.
