### ISSUE TITLE
Simplify the API

### ISSUE THREAD

**Issue by jimtyhurst** [hackoregon/team-budget#49]
## Summary
As a consumer of the API, I want to be able to retrieve budget data from multiple years, so that I can present it to people who want to review the budget.

## Current situation
As developers have been learning Django and developing iteratively, the API now has redundant endpoints that demonstrate different styles of implementation. For example, `/ocrb`, `/ocrb-prod`, and `/summary` all return budget data from the "Operating and Capital Requirements by Bureau" (OCRB) tables in the "Budget in Brief" brochures.

- `/ocrb` was developed first, as a quick prototype, which reads data directly from CSV files. It served that purpose well and allowed developers to demonstrate an API during the very first week that coding started. Unfortunately, it works around the Django framework's Model, which makes it difficult to implement filtering and sorting, because it is not using framework classes for the list of objects.
- `/summary` was developed next, taking advantage of the `importcsv.py` script, which allowed us to load the CSV files into a relational database. Initially, we used the embedded sqlite3 database for development, but the code works unchanged with the current PostgreSQL database running independently on an AWS EC2 instance. `/summary` was written during the second week and it enhanced the API to allow for query parameters to filter the data and it returns the data sorted in a standard order. It allows for case-insensitive matching of query parameter values to field values, but requires case-sensitive matching of query parameter names to field names.
- `/ocrb-prod` was developed the next week, taking advantage of the data which by this time was deployed in a PostgreSQL database on an AWS EC2 instance. This implementation uses an alternative approach for handling query parameters, which provides for more concise code, which can handle future query parameters without code changes. It requires exact case-sensitive matching of query parameter values to field values and exact case-sensitive matching of query parameter names to field names.

There are two endpoints for Key Performance Measure (KPM) data with parallel implementations to the corresponding OCRB endpoints:

- `/kpm` reads data from a CSV file.
- `/kpm-prod` reads data from the database configured in `project_config.py`.

## Desired situation
It is time to reconcile those different implementations, refactor, and present a simple API for accessing budget data with just one endpoint for OCRB data and one endpoint for Key Performance Measures (KPM).

It might just be as simple as choosing the latest implementation, but there are a few factors to consider, such as:

- Error handling, e.g. when client makes a call with a query parameter name that does not match an object field name.
- Extensibility, e.g. whether coding changes are required when new fields become available on the model objects.
- Case-sensitive vs insensitive query parameter names.
- Case-sensitive vs insensitive query parameter values.

**Comment by MikeTheCanuck** [comment]
FWIW, in my experience as a consumer of web APIs and web apps, I find it extremely frustrating to deal with case-sensitivity in either parameter names or values.  This is something that code automates quite well, removing the burden from the consumer to have to research documentation (where available) or to have to remember every time they attempt to use such endpoints.  

Yes *NIX starts out with this bias to case-sensitivity, but in practice where human interactions are concerned, most people find it confusing when two implementations give different results when case is the only variation, and thus if we're not intending to *implement* case-sensitive variants, I recommend we eliminate the case-sensitivity entirely.

**Comment by hassanshamim** [comment]
@jimtyhurst closed I believe.

**Comment by jimtyhurst** [comment]
Closed by merge of pull request #59, except for "Error handling, e.g. when client makes a call with a query parameter name that does not match an object field name." That requirement was not implemented. We decided that the extensibility was more important than the error checking, at least for the MVP, and you cannot have both.
