### ISSUE TITLE
Which version of Python should be used in Django app's Docker container?

### ISSUE THREAD

**Issue by MikeTheCanuck** [hackoregon/team-budget#50]
As @jimtyhurst [asked in PR47](https://github.com/hackoregon/team-budget/pull/47#issuecomment-285295058), we have so far arbitrarily assigned a version of Python to use in the Django app.

Currently the Dockerfile specifies `FROM python:3.5`, whereas the current version of Python is 3.6.0.

Is there any reason not to use Python 3.6?

**Comment by MikeTheCanuck** [comment]
I've tested the solution with the use of the `python:latest` base container image in PR #74 and it seems to be working, so I consider this resolved for the time being.

**Comment by jimtyhurst** [comment]
@MikeTheCanuck  reported an error with `python:latest` in Pull Request #81, but I think we should use `python:3.6.0` or `python:3.6`. I was able to build successfully with `FROM python:3.6.0` in the Dockerfile.

**Comment by jimtyhurst** [comment]
The problem is that the Docker image `python:latest` = `python:3.6.0` did not work on someone's Linux, so stay with `python:3.5` for now, which has worked on MacOS and Linux boxes.

**Comment by jimtyhurst** [comment]
Issue #85 was opened as a placeholder for future consideration of which Python version to use for running the team-budget application.
