### ISSUE TITLE
Enable functional testing of API container in Travis using "source env.sh" approach

### ISSUE THREAD

**Issue by MikeTheCanuck** [hackoregon/team-budget#61]
Goal: enable Travis to test the APIs running in Docker container e.g. using the `python manage.py test` pattern.

Approach selected: having run into a dead-end enabling the "import . from project_config" approach in issue #58, let's pursue the alternative approach raised at the Budget Team meeting on 2017-03-13: "source env.sh".

In this implementation, rather than download the `project_config.py` file and import it in `settings.py`, we'll download an `env.sh` file where all settings are `exported` as environment variables, that can be accessed by `settings.py` (and other bits of code).

This also shares implementation with the proposal by backend developers to allow them to switch database layers from AWS to any local database from their developer computers.

**Comment by MikeTheCanuck** [comment]
First attempt appears to work locally but in choosing the `build-test-proj.sh` script for Travis, we ended up with a familiar error:

```
Step 12 : WORKDIR /code
 ---> Running in 8023324e49d7
 ---> dadc58e6c1e3
Removing intermediate container 8023324e49d7
Successfully built dadc58e6c1e3
Build completed...
Start not executed yet...
Starting budget-service ... 
ERROR: No containers to start
Start completed...
Exec not started yet...
ERROR: No container found for budget-service_1
Exec completed...
```

See [Travis build 112](https://travis-ci.org/hackoregon/team-budget/builds/211063955) for details.

**Comment by MikeTheCanuck** [comment]
Subsequent attempt where we just launch the test directly against the container run into another problem - it appears the `source`'d env vars don't successfully pass through the `docker-compose.yml` bridge:

```
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.
```

See [Travis build 118](https://travis-ci.org/hackoregon/team-budget/builds/211086930) for details.

**Comment by MikeTheCanuck** [comment]
I just tried hard-coding the DJANGO_SECRET_KEY as a Travis env var (just to see if that would help the build proceed).

I still get this message during build: `WARNING: The DJANGO_SECRET_KEY variable is not set. Defaulting to a blank string.`

This indicates to me that the env.sh script overwrote the Travis setting with a blank value - i.e. that the `export DJANGO_SECRET_KEY='[string]'` statement in `env.sh` somehow overwrites the existing value with [null] or '' - maybe when it gets `source`'d it's behaving unexpectedly?

Or is this just another Travis-ism?

**Comment by MikeTheCanuck** [comment]
I even removed the '' around the `env.sh` values in case that was causing Travis to record the values as blank.  [Spoiler: it wasn't.]

Further, I hard-coded the `DATABASE_PORT=5432` value in `docker-compose.yml` just to prove to myself that if the value is available, Docker doesn't report it as blank.  [I was starting to lose my mind.]

Still getting "variable is not set".

See [Travis build 121](https://travis-ci.org/hackoregon/team-budget/builds/211125084) for details.

**Comment by BrianHGrant** [comment]
Hey so I tried the env variable pattern with the test repo. I tried two different builds:

1st - Did not escape the DJANGO_SECRET_KEY variable in any way in travis, (ie no quotes around it), this build failed with a similar error message to yours:

Travis Build 30: https://travis-ci.org/BrianHGrant/backend-service-pattern-travis/builds/211159139

Setting environment variables from repository settings
$ export DOCKER_REPO=[secure]
$ export DOCKER_IMAGE=[secure]
$ export DOCKER_USERNAME=[secure]
$ export DOCKER_PASSWORD=[secure]
$ export ECS_CLUSTER=[secure]
$ export DEPLOY_TARGET=[secure]
$ export PROJ_SETTINGS_DIR=[secure]
$ export CONFIG_BUCKET=[secure]
$ export AWS_DEFAULT_REGION=[secure]
$ export AWS_ACCESS_KEY_ID=[secure]
$ export AWS_SECRET_ACCESS_KEY=[secure]
$ export DATABASE_PORT=[secure]
$ export DATABASE_NAME=[secure]
$ export DATABASE_HOST=[secure]
$ export DATABASE_USER=[secure]
$ export DATABASE_PASSWORD=[secure]
$ export DJANGO_SECRET_KEY=[secure]
The previous command failed, possibly due to a malformed secure environment variable.
Please be sure to escape special characters such as ' ' and '$'.
For more information, see https://docs.travis-ci.com/user/encryption-keys.

2nd Attempt - using single quotes around the DJANGO_SECRET_KEY variable as it contains special charecters:

https://travis-ci.org/BrianHGrant/backend-service-pattern-travis/builds/211160342

Successfully rececognizes the variables, builds the container, and runs the python manage.py test script. This eventually time out but this is due to a non-existent test db. But the general architecture of travis using the env variables is working.

**Comment by MikeTheCanuck** [comment]
I have even attempted to `source` the `env.sh` script from within the Docker container.  I wrote a new script called `test-in-docker.sh`, and included two commands:

```
source /code/bin/env.sh
python manage.py test
```

This script was named in `docker-compose.yml` instead of `test-proj.sh` or `docker-entrypoint.sh`, and this still failed on "variable is not set".

See [Travis build 123]( https://travis-ci.org/hackoregon/team-budget/builds/211144657) for details.

**Comment by MikeTheCanuck** [comment]
Because I figured I was losing my mind, and needed to get grounded again, I HARD-CODED every single variable that appears in `env.sh` into the Travis repo settings.

This finally passed all the required steps:

```
Step 12 : WORKDIR /code
 ---> Running in b40c5ecef138
 ---> 62e87d9f9f6a
Removing intermediate container b40c5ecef138
Successfully built 62e87d9f9f6a
WARNING: Image for service budget-service was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Creating test database for alias 'default'...
----------------------------------------------------------------------
Ran 0 tests in 0.000s
OK
Destroying test database for alias 'default'...
The command "./budget_proj/bin/test-proj.sh" exited with 0.
Done. Your build exited with 0.
```

See [Travis build 124](https://travis-ci.org/hackoregon/team-budget/builds/211161652) for details.

This proves to me that the build steps work when we remove the steps that try to export and read environment variables from runtime scripts.

I am unsure if even the "source env.sh" approach is feasible given the problems I'm having making it work in Travis.

**Comment by MikeTheCanuck** [comment]
Holy crap Brian, I didn't even see your response here until I tried the same thing.  Yes, it looks like as long as the Django secret string is escaped, then hard-coding every single variable into the Travis repo Settings does work.

So we both have evidence that this whole build-and-test approach *can* successfully run in Travis.

**Comment by MikeTheCanuck** [comment]
I have reported this issue to TravisCI in case there is some systemic problem with TravisCI wiping out contents of env vars that we source from shell scripts:
https://github.com/travis-ci/travis-ci/issues/7472

**Comment by MikeTheCanuck** [comment]
I continue to be haunted by the fact that the env vars don't propagate from one script/command to the ones I need.  Constant management of variations on this error:

```
Running test_proj.sh...
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/commands/test.py", line 29, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 286, in run_from_argv
    parser = self.create_parser(argv[0], argv[1])
  File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 260, in create_parser
    self.add_arguments(parser)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/commands/test.py", line 56, in add_arguments
    test_runner_class = get_runner(settings, self.test_runner)
  File "/usr/local/lib/python3.5/site-packages/django/test/utils.py", line 138, in get_runner
    test_runner_class = settings.TEST_RUNNER
  File "/usr/local/lib/python3.5/site-packages/django/conf/__init__.py", line 53, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.5/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.5/site-packages/django/conf/__init__.py", line 116, in __init__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.
```

Switching back to issue #58 and re-trying the implementation of `project_config.py` download and import.  Wish me luck!

**Comment by MikeTheCanuck** [comment]
Also, I tried variations on `os.getenv()` instead of `os.environ.get()` but that isn't helping one bit:
http://stackoverflow.com/questions/16924471/difference-between-os-getenv-and-os-environ-get

**Comment by MikeTheCanuck** [comment]
With five weeks to go before Demo Day, it's time to park this issue.  We now have a working Travis/testing solution in PR #74, and this `env.sh` approach would require re-engineering Travis as well as local usage, so it's a non-starter (at least until the devops squad have free time, once we have all backend and frontend code deploying automatically).
