### ISSUE TITLE
Create a History Summary View

### ISSUE THREAD

**Issue by mxmoss** [hackoregon/team-budget#67]
User Story: As a customer who is also involved in cable access production, I want to know how much $$ goes to the Mt Hood Cable Regulatory Commission.  I guess this should be shown per year, so I can see the funding trend.

Steps to get the data:
1) Query the division code
> http://127.0.0.1:8000/code/?code_type=division_code

Here is a portion of the result...
>     {
>        "code_type": "division_code",
>        "code": "CBMH",
>        "description": "Mt Hood Cable Regulatory Commission"
>     },

2) Query the history for division_code = 'CBMH' fiscal_year 2011-12

> http://127.0.0.1:8000/history/?division_code=CBMH&fiscal_year=2011-12

Get a bunch of data elements similar to this:
>     {
>         "fund_center_code": "CBMH000001",
>         "fund_code": "GENERAL",
>         "functional_area_code": "CDCC00",
>         "object_code": "EMS",
>         "fund_center_name": "Mt. Hood Cable Regulatory Commission",
>         "fund_name": "General Fund",
>         "functional_area_name": "Cable Communications",
>         "accounting_object_name": "External Materials and Services",
>         "service_area_code": "CD",
>         "program_code": "CDCC",
>         "sub_program_code": "CDCC00",
>         "fund_center": "CBMH000001",
>         "division_code": "CBMH",
>         "bureau_code": "CB",
>         "bureau_name": "Office for Community Technology",
>         "fiscal_year": "2011-12",
>         "amount": 0
>     },
>     {
>         "fund_center_code": "CBMH000001",
>         "fund_code": "SPEC_REV",
>         "functional_area_code": "CDCC00",
>         "object_code": "IMS",
>         "fund_center_name": "Mt. Hood Cable Regulatory Commission",
>         "fund_name": "Special Revenue",
>         "functional_area_name": "Cable Communications",
>         "accounting_object_name": "Internal Materials and Services",
>         "service_area_code": "CD",
>         "program_code": "CDCC",
>         "sub_program_code": "CDCC00",
>         "fund_center": "CBMH000001",
>         "division_code": "CBMH",
>         "bureau_code": "CB",
>         "bureau_name": "Office for Community Technology",
>         "fiscal_year": "2011-12",
>         "amount": 99187
>     },
 

3) Sum all the amounts
Right now, summing is done on the front end- either by a human or a computer.

Questions/ Comments:
1) I guess we should also create a code set for the fiscal years
2) How will users know what divisions to look for?
  Either (a) they have a picklist or (b) they can enter a portion of the string
  Probably picklist is the better option?
3) We don't really need to return _all_ of these fields (fund_center_code & fund_center? sub_program_code?) but let's keep them for now.
4) Are the amounts in dollars or pennies? Just a question for QA
5) The key point is... we currently have history "detail" mode - returning the detail of the search.
  Let's also consider a "history summary" mode - returning the sum of amounts for a search.

This summary would return:
- the columns that were searched for (ie: division_code & fiscal_year)
- the sum of all amounts

**Comment by jimtyhurst** [comment]
I was thinking of something very similar. We need to enhance the API to return very specific data to support the MVP. One of the scenarios we saw in the wireframe was total amount by service area per year. The next level down was total amount per bureau by year. I think those should be two different endpoints that do the summation on the server and return precisely the data needed by the UI.

**Comment by mxmoss** [comment]
This story was made obsolete by #75 and  #76
