### ISSUE TITLE
Create data endpoint for the total budget by Service Area

### ISSUE THREAD

**Issue by mxmoss** [hackoregon/team-budget#75]
Create data endpoint for the total budget by Service Area
Filter by Fiscal Year
Result: See example (below). Amount in dollars
Concern: How to create a summary endpoint?
Example results  (Amounts not accurate)

Svc Area    |   Fiscal Yr | Object Code | Amount
-----------------------------------------------------
Pub. Safety | 2014-15     | Personal    | $140,034,432
Pub. Safety | 2014-15     | IMS         | $153,234,432
Pub. Safety | 2014-15     | EMS         | $134,344,432
Parks       | 2014-15     | Personal    |  $34,024,432
Parks       | 2014-15     | IMS         |  $43,444,334
Parks       | 2014-15     | EMS         |  $85,343,324
Pub. Util   | 2014-15     | Personal    | $123,343,234
Pub. Util   | 2014-15     | IMS         | $163,344,324
Pub. Util   | 2014-15     | EMS         | $173,432,342

**Comment by jimtyhurst** [comment]
I would like to see this endpoint implemented as:
- _URI_: /history/service_area/
- _Optional query parameters_: fiscal_year, service_area_code, object_code
- _Response fields_: `fiscal_year`, `service_area_code`, `service_area`, `object_code`, `accounting_object_name`, `amount`

where all fields are strings, except the `amount`, which is an integer (no dollar sign).

**Comment by mxmoss** [comment]
We talked & agreed the endpoint should return these values:
- fiscal_year
- service_area_code
- sum of amount

Two more items are desired, but won't be implemented for this story:

- service_area_name
- % of total

**Comment by mxmoss** [comment]
This has been implemented with the HistorySummaryByServiceArea endpoint and the aggregation by service area is correct. Closing this issue.
