### ISSUE TITLE
Create data endpoint for the Bureau totals for a Service Area

### ISSUE THREAD

**Issue by mxmoss** [hackoregon/team-budget#76]
Create data endpoint for the Bureau totals for a Service Area
Filtered by
- Service Area
- Fiscal Year
Return Amount in dollars
Example results  (Amounts not accurate)

Service Area = Public Safety
Bureau      |   Fiscal Yr | Object Code | Amount
-----------------------------------------------------
Emergency Comm. | 2014-15     | Personal    | $140,034,432
Emergency Comm. | 2014-15     | IMS         | $153,234,432
Emergency Comm. | 2014-15     | EMS         | $134,344,432
Emergency Mgmt. | 2014-15     | Personal    |  $34,024,432
Emergency Mgmt. | 2014-15     | IMS         |  $43,444,334
Emergency Mgmt. | 2014-15     | EMS         |  $85,343,324
PPB             | 2014-15     | Personal    | $123,343,234
PPB             | 2014-15     | IMS         | $163,344,324
PPB             | 2014-15     | EMS         | $173,432,342

**Comment by mxmoss** [comment]
We talked & decided to return these fields:

- fiscal_year
- service_area_code
- bureau_code
- bureau_name
- sum of amount

These fields are desired, but not implemented in this story:

- service_area_name
- % of total
-

**Comment by jimtyhurst** [comment]
Partially implemented by Pull Request #108. Remaining work is specified in Issue #132 and Issue #133.
