### ISSUE TITLE
Create data endpoint for showing budget data change over time

### ISSUE THREAD

**Issue by mxmoss** [hackoregon/team-budget#77]
Create data endpoint for showing budget data change over time
Want to show the change in budget totals by service area for each fiscal year
Result is in dollars per service area per fiscal year
Consider that this data will be used in a Sankey diagram or stream graph

**Comment by mxmoss** [comment]
I think this issue has been satisfied by the /budget/history/service_area endpoint
(implemented by HistorySummaryByServiceArea)

**Comment by MikeTheCanuck** [comment]
If the OP (Moss) believes this is addressed, then I'll close it and it can be reopened with a more specific, explicit ask in the future, if need be.
