### ISSUE TITLE
PROBLEM: History and OCRB endpoints give 502/504 response in AWS

### ISSUE THREAD

**Issue by MikeTheCanuck** [hackoregon/team-budget#87]
As Jim pointed out in his comments on PR #86, the /ocrb and /history endpoints are behaving poorly.  

"When accessing the services on AWS, I get a `502 Gateway Error` for these two URLs:
```
# Returns 502
http://hacko-integration-658279555.us-west-2.elb.amazonaws.com/budget/ocrb/
http://hacko-integration-658279555.us-west-2.elb.amazonaws.com/budget/history/
```
but I get 200 OK and data when I supply query parameters. For example:
```
# Returns 200 OK
http://hacko-integration-658279555.us-west-2.elb.amazonaws.com/budget/ocrb/?fy=2015-16
http://hacko-integration-658279555.us-west-2.elb.amazonaws.com/budget/history/?fiscal_year=2015-16&bureau_code=PS
```
I am wondering if there is too much data for the bare endpoints /ocrb and /history. That could definitely be a problem for /history, which is a fairly large data set. In contrast, I do _not_ see any problems with bare /kpm:
```
# No problems with these URLs:
http://hacko-integration-658279555.us-west-2.elb.amazonaws.com/budget/kpm/
http://hacko-integration-658279555.us-west-2.elb.amazonaws.com/budget/code/
```

I've since observed 504 errors as well (Gateway Timeout), but haven't inferred a pattern.

**Comment by MikeTheCanuck** [comment]
My first thought was "we might be hitting CPU or memory contention", but the logs don't *look* like we're having that kind of problem (though it's possible the acute spikes are being squashed in this timespan):

![image](https://cloud.githubusercontent.com/assets/6953053/24231849/42abe720-0f44-11e7-8bb5-dbc9e6e40d55.png)

![image](https://cloud.githubusercontent.com/assets/6953053/24231852/478f16b8-0f44-11e7-8f0a-2162e243c542.png)

I *am* concerned either way - this is not what we expect from the cloud - and I know these endpoints are still working fine when I test the local container, so the database is likely not the issue (if it was, the problem would be worse when I sent queries from my laptop over the Internet, than when we send queries from the EC2-hosted API to the EC2-hosted postgres).

**Comment by hassanshamim** [comment]
I think I got this one.  Creating a branch now.

**Comment by hassanshamim** [comment]
Noope.  Still not fixed, I'll investigate further.

**Comment by hassanshamim** [comment]
So I'm 99% sure the problem here is the size of the responses.  We haven't added pagination yet.  In the process of generating test fixtures I dumped our models as json data and found that the history.json is 61 MB and the OCRB is 4.6 MB.  The first is obviously wayy to large to to be serving straight up like that.  Plus serializing data actually takes some time.

Dunno how high-priority this is as we have raw json files for the frontend to work off of for now but this will get resolved when I add pagination.

**Comment by jimtyhurst** [comment]
I agree that this is almost certainly a problem with the response being too large. Therefore, paging will very likely solve this problem.

**Comment by MikeTheCanuck** [comment]
@mxmoss and I hacked on this a little and came up with some promising results:
1. Tried adding additional query parameters in the queries until we got to some that finally returns a result under the load balancer's timeout value e.g. http://hacko-integration-658279555.us-west-2.elb.amazonaws.com/budget/history/?fiscal_year=2015-16&fund_code=SPEC_REV&object_code=CAPITAL
2. Added an index to the `fiscal_year` column in the `budget_app_budgethistory`, and all queries returned faster, even if the broadest queries still couldn't defeat the timeout.

These give us a couple of levers to pull on.

**Comment by mxmoss** [comment]
I committed the [SQL to create the index here] ( https://github.com/hackoregon/team-budget/blob/master/sql/idx_budgethistory_FY.sql)

**Comment by hassanshamim** [comment]
Closed by #112, all the above endpoints are working now.

**Comment by MikeTheCanuck** [comment]
@hassan what do you believe the solution is that allows us to consider this matter closed (and not just "not currently present")?

**Comment by hassanshamim** [comment]
@MikeTheCanuck  I believe it was the introduction of paginated responses.  The original URIs that were failing were all full-table responses while the mysteriously-working queries had some filtering on them.  The fact that you could 'drill down' with query params until the server would return 200 supports this theory a bit.

I have no way of verifying this though as I couldn't replicate original problem locally in docker.

Feel free to reopen this though - you're right in that my thinking was 'no longer present -> closed'.
