### ISSUE TITLE
View Query param filtering

### ISSUE THREAD

**Issue by hassanshamim** [hackoregon/team-budget#90]
So just ran into this scenario:

We want to pass query params to a view that *do not* map to a model field.  An example of this would be `?format=json`, which is one way DRF can decide to render a JSON response rather than HTML for the exploreable API.  With our current query filtering we get an error like this:

http://hacko-integration-658279555.us-west-2.elb.amazonaws.com/budget/ocrb/?format=json

When it should just return a json response, like the KPM endpoint does (no filtering implemented)
http://hacko-integration-658279555.us-west-2.elb.amazonaws.com/budget/kpm/?format=json

Possible solutions:
1.  install and use the [django-filter](https://github.com/carltongibson/django-filter) package
2.  write our own class/function that does the filtering as necessary.

Number 2 will have to cover:
- differentiate query params that filter and those that modify the request
- aggregrate params and compare to model fields.
- decide how to handle invalid params.

I vote Number 1 as I see it as the *better* solution.  That said, Number 2 sounds like more fun.

**Comment by MikeTheCanuck** [comment]
Number 1 sounds like the smarter choice to get us going.  It'll be easier for other/new folks to research (if they don't know how it works) or just use it (if they're already familiar with Django).

**Comment by hassanshamim** [comment]
Closed by #112
