### ISSUE TITLE
Improve startup response from the Django app (to solve AWS deploy blocker)

### ISSUE THREAD

**Issue by MikeTheCanuck** [hackoregon/team-budget#96]
Brian Grant and I have been working all this week to find a way to stabilize the Docker containers in AWS.

Problem is, the containers deploy and start fine, but the app inside them doesn't respond quickly enough for the AWS "Health Check" to consider them healthy containers, so they never get scheduled in rotation by the load balancers.  Instead, AWS automatically starts new containers from the same deployed image and replaces the "unhealthy" containers.  However, since the image is the same every time, AWS can never get "healthy" containers.

End result: Budget is running on ancient code, and can't be updated in AWS until the code in the container image stabilizes.

Current hypothesis (advanced by Dan, and which fits all the behaviours I've observed to date) is this: in looking at the code in `views.py`, it appears the app is loading all unfiltered models at startup, which means it's loading the entire database table at startup.  And since some of the tables are outsized, this is causing the startup to slow down until it exceeds all reasonable timeouts for determining that the contents of the container are healthy enough to be put into rotation.

According to the second article below, "Django load all applications and their 'models.py' at startup and executes its code."

Dan fired a number of resources my way, and while I'd love to use them to resolve the problem, this isn't a great use of my limited Python skills.  This could use some app dev expertise.  Can any of you folks help out?

Here's the links:
https://docs.djangoproject.com/en/1.10/topics/performance/
http://kartowicz.com/dryobates/2014-10/queries-run-django-projects-startup/
https://gun.io/blog/fast-as-fuck-django-part-1-using-a-profiler/

**Comment by hassanshamim** [comment]
I don't think it querying the database on startup is the issue here.

Added the following to my dev settings to log django SQL queries to my console:

```python
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
        }
    },
    'loggers': {
        'django.db.backends': {
            'handlers': ['console'],
            'level': 'DEBUG',
        },
    }
}
```

And then ran the server:

```
pm runserver                                                                                                                                            [19:57:34]
Performing system checks...

System check identified no issues (0 silenced).
(0.001)
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
(0.001) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
April 02, 2017 - 02:57:37
Django version 1.10.5, using settings 'budget_proj.settings.dev'
Starting development server at http://127.0.0.1:8000/
```

You can see it only made 2 queries: one to find/test the database and the other to find/test the migrations.  Once I started hitting API endpoints then I'd see SQL queries again.  We aren't caching/preloading rows from the database right now.

**Comment by MikeTheCanuck** [comment]
Well damn. That's good for smart Django behaviour but terrible for helping us figure out what the hell never responds within something like 30-40 seconds when the container starts and the load balancer sends /budget/ request to gunicorn.

**Comment by MikeTheCanuck** [comment]
BTw thanks for doing that tracing - I couldn't figure out what to do to expose that startup activity.

**Comment by znmeb** [comment]
Easy question: 

1. How much RAM does the server have?
2. Can you add more?
3. Does it help?

**Comment by MikeTheCanuck** [comment]
A few changes have been made lately to massively improve/stabilize the startup behaviour:
1. Larger AWS hosts have been deployed to serve the array of containers we have deployed.
2. AWS load balancer timeouts have been reduced to keep from leaving terrible containers in play.
3. Gunicorn timeouts and workers have been reduced to a level that is eliminating the CRITICAL WORKER TIMEOUT phenomenon across all the backend projects.

While there are Django projects this season that are currently performing non-trivial startup behaviour (including running init code in their data models), those issues do not appear to be manifest in the current Budget Django code.
